# Generated by Django 6.0.3 on 2026-04-02 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='상품명')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='슬러그')),
                ('image', models.ImageField(upload_to='products/', verbose_name='상품이미지')),
                ('short_description', models.CharField(max_length=200, verbose_name='짧은 설명')),
                ('description', models.TextField(verbose_name='상세 설명')),
                ('price', models.PositiveIntegerField(verbose_name='가격')),
                ('size', models.CharField(blank=True, max_length=100, verbose_name='규격')),
                ('is_active', models.BooleanField(default=True, verbose_name='진열 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '상품',
                'verbose_name_plural': '상품',
                'ordering': ['id'],
            },
        ),
    ]
