# Generated by Django 6.0.3 on 2026-04-08 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_is_featured_product_featured_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['featured_order', 'id'], 'verbose_name': '상품', 'verbose_name_plural': '상품'},
        ),
    ]
